### PR TITLE
Update OpenGL for Processing 2.1

### PR DESCRIPTION
**Pull request by ThomasLengeling**
Only tested on a windows 8 64bits

### CODE REVIEW

**Comment by jesperalmstrom** [comment]
Changes to get MSAFluid example to work with Processing 2.1.1

Followed this example:
http://wiki.processing.org/w/Vertex_Buffer_Object_(VBO) to be able to
get the example to work with Processing 2.1.1

Recompiled the MSAFluid.jar with Java JDK 1.7.0_17

Created a Eclipse project for the MSAFluid library.

Rebuilt the JavaDoc with Java 7
It is working on Mac OSX 10.9.2 with default Java 7. 
I would like to contribute my changes to the project.

**Comment by aronaltmark** [comment]
@jesperalmstrom Would be very interested to take a look at your updated code, I'm digging in to work on the same issue.

**Comment by jesperalmstrom** [comment]
Great to hear that you are interested. I have committed my changes here: https://github.com/jesperalmstrom/p5-MSAFluid
My next step is to combine the MSAFluid demo with the Kinect using Simple-OpenNI lib.

**Comment by aronaltmark** [comment]
Excellent! I see I was on the right track, but not quite there. Thanks for sharing. Also working on a similar project.

**Comment by omarojo** [comment]
@jesperalmstrom Wow :+1:  !! your MSAFluidOpenKinect example is awesome.. well all the code is just too complicated for me to understand. Example runs fine in my Mac. I wanted to use the whole body point cloud to affect the MSAFluid using SimpleOpenNI, but then it was too difficult for me, so I used the tracking hands example from SimpleOpenNI and managed to somehow make it work applying the force to the fluid, but with a constant velocity :(. But your OpenKinect example is just out of my league, I would never be able to code all that, thats too much math. 

btw I previously found this fork, that makes MSAFluid work with Processing 2.1 and didn't have to recompile the MSAFluid Library, I think this guy uses a different approach.
https://github.com/ThomasLengeling/p5-MSAFluid/tree/master/examples/MSAFluidDemo

Taking advantage of this post, do you know how is this project done ? https://www.youtube.com/watch?feature=player_embedded&v=ISKV1BeB3pM
I want to do something similar, seems that your example might do something similar.

Congratz

**Pull request merged**
